@startuml add-product
title Add Product
actor User

User -> Kong : addProduct(name: String, category: String, price:Number)
Kong -> ProductService : addProduct(name: String, category: String, price:Number)
ProductService --> Kong  :Success
Kong --> User : Success
@enduml