@startuml search-product
title Seach Product
actor User

User -> Kong : searchForProduct(id:Number, name:String, category:String)
Kong -> ProductService : searchForProduct(id:Number, name:String, category:String)
ProductService --> Kong : Product
Kong --> User : Product

@enduml