@startuml update-product
title Update Product
actor User

User -> Kong : updateProduct(id:Number, name: String, category: String, price:Number)
Kong -> ProductService : updateProduct(id:Number, name: String, category: String, price:Number)
ProductService --> Kong : Product
Kong --> User : Product
@enduml