services:
  shop:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true 
    tty: true  
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres_db:5432/shop
    command: sh -c "npx prisma db push && npm run api"
    ports:
      - "3000:3000"
  db:
    image: postgres
    hostname: postgres_db
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    