services:
  shop1:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile 
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres_db:5432/shop
      REDIS_URL: redis://redis:6379
      PORT: 3000
    command: sh -c "npx prisma db push && npm run api"
    expose:
      - "3000"
  shop2:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile 
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres_db:5432/shop
      REDIS_URL: redis://redis:6379
      PORT: 3000
    command: sh -c "npx prisma db push && npm run api"
    expose:
      - "3000"
  shop3:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile 
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres_db:5432/shop
      REDIS_URL: redis://redis:6379
      PORT: 3000
    command: sh -c "npx prisma db push && npm run api"
    expose:
      - "3000"
  db:
    image: postgres
    hostname: postgres_db
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: shop
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - shop1
      - shop2
      - shop3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"