services:
  lab1:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: lab1
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres_db:5432/lab1
    image: lab1
    command: sh -c "npx prisma migrate deploy && npm start"
    ports:
      - "3000:3000"
  db:
    image: postgres
    hostname: postgres_db
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: lab1
    ports:
      - "5432:5432"
    