global:
  scrape_interval: 20s

scrape_configs:
  - job_name: kong
    static_configs:
      - targets: ['kong:8001']

  - job_name: microservice
    static_configs:
      - targets: 
        - 'product-service:3000' 
        - 'sales-service:3000' 
        - 'stocks-service:3000'
        - 'account-service:3000'
        - 'checkout-service:3000'
        - 'shopping-cart-service:3000'