@startuml get-stocks
actor StoreEmployee

StoreEmployee -> StoreEmployeeView : getStocks()
StoreEmployeeView -> StoreEmployeeController : getStocks()
StoreEmployeeController --> StoreEmployeeView : Stocks for all product
StoreEmployeeView --> StoreEmployee : Stocks for all product
@enduml