@startuml save-sales
title Save Sales
actor StoreEmployee

StoreEmployee -> StoreEmployeeView : addSales(sales:Sales)
StoreEmployeeView -> StoreEmployeeController : addSales(sales:Sales)
StoreEmployeeController --> StoreEmployeeController : updateStocksCount()
StoreEmployeeController --> StoreEmployeeView : Done
StoreEmployeeView --> StoreEmployee : Done
@enduml