@startuml clear-cart
title Clear cart
actor User

User -> Kong : ClearCart(storeId: Number, accountId: Number)
Kong -> ShoppingCartService : ClearCart(storeId: Number, accountId: Number)
ShoppingCartService --> StocksService : decrementStocks(productId: Number, amount: Number, storeId: Number)
StocksService --> ShoppingCartService : Done
ShoppingCartService --> Kong : Done
Kong --> User : Done
@enduml