' @startuml get-cart
' title Get cart
' actor User

' User -> Kong : GetCart(storeId: Number, accountId: Number): Sales
' Kong -> ShoppingCartService : GetCart(storeId: Number, accountId: Number): Sales
' ShoppingCartService --> Kong : Sales
' Kong --> User : Sales
' @enduml