@startuml saga
[*] --> StocksChecked
StocksChecked --> [*] : Not enough stocks
StocksChecked --> StocksReduced : Enough stocks
StocksReduced --> ShoppingCartCreated
ShoppingCartCreated --> StocksReverted : Shopping cart already exist
ShoppingCartCreated --> ShoppingCartFetch
ShoppingCartFetch --> PriceFetched

PriceFetched --> PaymentAccepted : Payment is higher than fetched price
PaymentAccepted --> SalesAdded
SalesAdded --> ShoppingCartDeleted


PriceFetched --> PaymentRefused : Payment is lower than fetched price
PaymentRefused --> StocksReverted

ShoppingCartDeleted --> SagaEnded
StocksReverted --> ShoppingCartDeleted

SagaEnded --> [*]
@enduml