@startuml get-stocks
title Get Stocks
actor User

User -> Kong : getStocks(productId: Number, storeId: Number)
Kong -> StockService : getStocks(productId: Number, storeId: Number)
StockService --> Kong : Stocks
Kong --> User : Stocks
@enduml