@startuml get-order
title Get Order
actor User

User -> Kong : getOrder(productId: Number, storeId: Number)
Kong -> StockService : getOrder(productId: Number, storeId: Number)
StockService --> Kong : Order
Kong --> User : Order
@enduml