' @startuml checkout-sale
' title Checkout sale
' actor User

' User -> Kong :checkoutSale(storeId: Number, accountId: Number)
' Kong -> OnlineSalesOrchestator : checkoutSale(storeId: Number, accountId: Number)
' OnlineSalesOrchestator -> StocksService : decrementStocks(productId: Number, amount: Number, storeId: Number)
' StocksService --> CheckoutService  :Success
' CheckoutService --> Kong  :Success
' Kong --> User : Success
' @enduml