@startuml class
class StoreEmployee {
    + searchForProduct(id:Number, name:String, category:String): Product
    + addSales(sales: Sales): Void
    + cancelSales(id: Number): Void    
    + getStocks(): Void
    + orderMoreStocks(productId: Number, amount: Number): Void
}

class SupplyCenterEmployee {
    + deliverStocks(productId: Number, storeId: Number): Void
}

class Manager {
    + addProduct(name: String, category: String, price:Number): Void
    + updateProduct(id:Number, name: String, category: String, price:Number): Void
    + getSalesReport(): String
    + getDashboardView(): String
}

class Product {
    id: Number
    name: String
    category: String
    price: Number
}

class Sales {
    date: DateTime
    isCancelled: Boolean
    storeId: Number
    + getPriceTotal(): Number
}

class Stock {
    amount: Number
    storeId: Number
}

class Order {
    amount: Number
    storeId: Number
}

class ProductSales {
    amount: Number
}

StoreEmployee ..> Sales

StoreEmployee ..> Product

StoreEmployee ..> Stock

StoreEmployee ..> Order

SupplyCenterEmployee --|> StoreEmployee

Manager --|> SupplyCenterEmployee

Sales "1" *-- "*" ProductSales

ProductSales "*" o-- "1" Product

Stock "*" o-- "1" Product

Order "*" o-- "1" Product
@enduml