@startuml component

package "Client" {
    component app.ts
    component server.ts
}

package "Prisma" {
    component schema.prisma
}

database "Server (PostgreSQL)" as Server

app.ts ..> schema.prisma
schema.prisma ..> Server


@enduml