@startuml component
skinparam componentStyle rectangle
skinparam defaultTextAlignment center

package "API Gateway" {
  [Kong]
}

package "Monitoring" {
  [Prometheus]
  [Grafana]
}

package "Shared Code" {
  [shared-utils] as SharedUtils
}

cloud "Kafka" {
}

package "Microservices" {
  component Product
  component Sales
  component Stocks
  component Account
  component ShoppingCart
  component Checkout
}

database "ProductDB" as dbProduct
database "SalesDB" as dbSales
database "StocksDB" as dbStocks
database "AccountDB" as dbAccount
database "CartDB" as dbCart
database "CheckoutDB" as dbCheckout


Kong --> Product
Kong --> Sales
Kong --> Stocks
Kong --> Account
Kong --> ShoppingCart
Kong --> Checkout

SharedUtils ..> Product
SharedUtils ..> Sales
SharedUtils ..> Stocks
SharedUtils ..> Account
SharedUtils ..> ShoppingCart
SharedUtils ..> Checkout

Product --> dbProduct
Sales --> dbSales
Stocks --> dbStocks
Account --> dbAccount
ShoppingCart --> dbCart
Checkout --> dbCheckout

Sales --> Kafka
Stocks --> Kafka
ShoppingCart --> Kafka
Checkout --> Kafka

Prometheus --> Product
Prometheus --> Sales
Prometheus --> Stocks
Prometheus --> Account
Prometheus --> ShoppingCart
Prometheus --> Checkout

Grafana --> Prometheus

@enduml
