@startuml component
title Component Diagram
package "Controller" {
    component "manager.ts" as manager
    component "store-employee.ts" as storeEmployee
    component "supply-center-employee.ts" as supplyCenterEmployee
}

package "View" {
    component "manager-views" as managerView
    component "store-employee-views" as storeEmployeeView
    component "supply-center-employee-views" as supplyCenterEmployeeView
    component "main-menu-views" as mainMenuView
}

package "Prisma" {
    component schema.prisma
}

database "Server (PostgreSQL)" as Server

schema.prisma ..> Server

supplyCenterEmployeeView ..> supplyCenterEmployee
managerView ..> manager
storeEmployeeView ..> storeEmployee
storeEmployee ..> schema.prisma
manager ..> schema.prisma
supplyCenterEmployee ..> schema.prisma
mainMenuView ..> storeEmployeeView
mainMenuView ..> managerView
mainMenuView ..> supplyCenterEmployeeView

@enduml