@startuml deployement
title Deployement Diagram

node "Monitoring container" {
    artifact Prometheus
    artifact Grafana
}

node "Kong" {

}


node "Product Database" {
    database "PostgreSQL" as ProductDB
}

node "Product Service"  {
    artifact ProductServer
    artifact ProductService
    artifact "Prisma" as ProductPrisma
}

    [Kong] --> [ProductServer]
    [ProductServer] --> [ProductService]
    [ProductService] --> [Prometheus]
    [ProductService] --> [ProductPrisma]
    [ProductPrisma] --> [ProductDB]

node "Sales Database" {
    database "PostgreSQL" as SalesDB
}

node "Sales Service"  {
    artifact SalesServer
    artifact SalesService
    artifact "Prisma" as SalesPrisma
}

    [Kong] --> [SalesServer]
    [SalesServer] --> [SalesService]
    [SalesService] --> [Prometheus]
    [SalesService] --> [SalesPrisma]
    [SalesPrisma] --> [SalesDB]

node "Stocks Database" {
    database "PostgreSQL" as StocksDB
}

node "Stocks Service"  {
    artifact StocksServer
    artifact StocksService
    artifact "Prisma" as StocksPrisma
}

    [Kong] --> [StocksServer]
    [StocksServer] --> [StocksService]
    [StocksService] --> [Prometheus]
    [StocksService] --> [StocksPrisma]
    [StocksPrisma] --> [StocksDB]



node "Account Database" {
    database "PostgreSQL" as AccountDB
}

node "Account Service"  {
    artifact AccountServer
    artifact AccountService
    artifact "Prisma" as AccountPrisma
}

    [Kong] --> [AccountServer]
    [AccountServer] --> [AccountService]
    [AccountService] --> [Prometheus]
    [AccountService] --> [AccountPrisma]
    [AccountPrisma] --> [AccountDB]

node "ShoppingCart Database" {
    database "PostgreSQL" as ShoppingCartDB
}

node "ShoppingCart Service"  {
    artifact ShoppingCartServer
    artifact ShoppingCartService
    artifact "Prisma" as ShoppingCartPrisma
}

    [ShoppingCartServer] --> [ShoppingCartService]
    [ShoppingCartService] --> [Prometheus]
    [ShoppingCartService] --> [ShoppingCartPrisma]
    [ShoppingCartPrisma] --> [ShoppingCartDB]

artifact Kafka

node "Package Service" {
    artifact PackageServer
    artifact PackageService
}

    [Kong] --> [PackageServer]
    [PackageServer] --> [PackageService]
    [PackageService] --> [Kafka]
    [PackageService] --> [Prometheus]

node "EventStore Service"{
    artifact EventStoreServer
    artifact EventStoreService
    artifact "Prisma" as EventStorePrisma
}

node "EventStore Database" {
    database "PostgreSQL" as EventStoreDB
}

    [Kafka] --> [EventStoreServer]
    [Kong] --> [EventStoreServer]
    [EventStoreServer] --> [EventStoreService]
    [EventStoreService] --> [EventStorePrisma]
    [EventStorePrisma] --> [EventStoreDB]
    [EventStoreService] --> [Kafka]
    [EventStoreService] --> [Prometheus]

node "Email Service"{
    artifact EmailServer
}

    [Kafka] --> [EmailServer]


node "Online Sales Orchestrator"  {
    artifact SalesOrchestator
    artifact SalesOrchestatorService
}

    [Kong] --> [SalesOrchestator]
    [SalesOrchestator] --> [SalesOrchestatorService]
    [SalesOrchestatorService] --> [Prometheus]

    [SalesOrchestatorService] --> [ShoppingCartServer]
    [SalesOrchestatorService] --> [ProductServer]
    [SalesOrchestatorService] --> [SalesServer]
    [SalesOrchestatorService] --> [StocksServer]



    [Prometheus] --> [Grafana]
@enduml