@startuml cancel-sales
title Cancel Sales
actor StoreEmployee

StoreEmployee -> StoreEmployeeView : cancelSales(id:Number)
StoreEmployeeView -> StoreEmployeeController : cancelSales(id:Number)
StoreEmployeeController --> StoreEmployeeController : updateStocksCount()
StoreEmployeeController --> StoreEmployeeView : Done
StoreEmployeeView --> StoreEmployee : Done
@enduml