@startuml cancel-sales
title Cancel Sales
actor User

User -> Kong : cancelSales(salesId: String, storeId: Number)
Kong -> SalesService : cancelSales(salesId: String, storeId: Number)
SalesService --> StocksService : incrementStocks(productId: Number, amount: Number, storeId: Number)
StocksService --> SalesService : Done
SalesService --> Kong : Done
Kong --> User : Done
@enduml