@startuml create-sales
title Create Sales
actor User

User -> Kong : createSales(productSales: ProductSales, storeId: Number)
Kong -> SalesService : createSales(productSales: ProductSales, storeId: Number)
SalesService --> StocksService : decrementStocks(productId: Number, amount: Number, storeId: Number)
StocksService --> SalesService : Done
SalesService --> Kong : Done
Kong --> User : Done
@enduml