name: CI - Checkout Service

on: push

jobs:
  Pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build project 
        working-directory: ./
        run: npm ci

      - name: Build shared-utils
        working-directory: ./src/shared-utils
        run: npm run build

      - name: Run eslint 
        working-directory: ./
        run: npx eslint
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: src/module/stocks/Dockerfile
          push: true
          context: .
          tags: pebrassard/lab5_checkout:latest
