name: CI - Online Sales Orchestrator

on: push

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    env: 
      PRODUCT_SERVICE_URL: http://product-service:3000
      STOCKS_SERVICE_URL: http://stocks-service:3000
      SALES_SERVICE_URL: http://sales-service:3000
      SHOPPING_CART_SERVICE_URL: http://shopping-cart-service:3000

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build project 
        working-directory: ./
        run: npm ci

      - name: Build shared-utils
        working-directory: ./src/shared-utils
        run: npm run build

      - name: Run eslint 
        working-directory: ./
        run: npx eslint

      - name: Run test 
        working-directory: ./
        run: npm run test:onlineSalesOrchestrator
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: src/module/product/Dockerfile
          context: .
          tags: pebrassard/lab6_online_sales_orchestrator:latest
