name: CI - Sales Service

on: push

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5434:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: sales
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env: 
      DATABASE_URL: postgresql://postgres:123@localhost:5434/sales

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build project 
        working-directory: ./
        run: npm ci

      - name: Build shared-utils
        working-directory: ./src/shared-utils
        run: npm run build

      - name: Generate Prisma
        working-directory: ./src/module/sales
        run: npx prisma generate

      - name: Push prisma
        working-directory: ./src/module/sales
        run: npx prisma db push

      - name: Run eslint 
        working-directory: ./
        run: npx eslint

      - name: Run test 
        working-directory: ./
        run: npm run test:sales
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: src/module/sales/Dockerfile
          push: true
          tags: pebrassard/lab5_sales:latest
